### ISSUE TITLE
There is no way to add space between Json Key and Value

### ISSUE THREAD

**Issue by AllanOricil** [chenfengjw163/vue-json-viewer#67]
All the Key, Value pairs are rendered without any spaces between them and there is no way to add it.

![image](https://user-images.githubusercontent.com/55927613/104134462-8314d800-5381-11eb-9ee9-d72997814aa9.png)

This is what I wanted. There is a single space between each key, value

![image](https://user-images.githubusercontent.com/55927613/104134486-ac356880-5381-11eb-979a-00051d315a27.png)

**Comment by AllanOricil** [comment]
Actually, there is a way

![image](https://user-images.githubusercontent.com/55927613/104134512-f880a880-5381-11eb-8a1a-30ee9437bbd8.png)

**Comment by AllanOricil** [comment]
I had to add the following css to the index.html to make the padding work

````css
.jv-key {
      color: var(--vscode-input-foreground) !important;
      padding-right: 5px !important;
  }
````
